//! Abstract Syntax Tree (AST) definitions for `omnitrade-script`.
//!
//! Defines expressions, statements, binary operators, and output signals
//! used by the script parser and evaluator.

/// Binary operators supported in strategy expressions.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinaryOp {
    /// Addition operator (`+`).
    Add,
    /// Subtraction operator (`-`).
    Sub,
    /// Multiplication operator (`*`).
    Mul,
    /// Division operator (`/`).
    Div,
    /// Greater-than operator (`>`).
    Gt,
    /// Less-than operator (`<`).
    Lt,
    /// Greater-than-or-equal operator (`>=`).
    Gte,
    /// Less-than-or-equal operator (`<=`).
    Lte,
    /// Equality operator (`==`).
    Eq,
    /// Inequality operator (`!=`).
    Neq,
    /// Logical AND operator (`&&`).
    And,
    /// Logical OR operator (`||`).
    Or,
}

/// Abstract Syntax Tree node for expressions.
#[derive(Debug, Clone, PartialEq)]
pub enum Expr {
    /// Numeric literal value (64-bit float).
    Number(f64),
    /// Variable identifier name.
    Identifier(String),
    /// Binary operator expression with left and right sub-expressions.
    BinaryOp {
        /// Left-hand operand.
        left: Box<Expr>,
        /// Binary operator.
        op: BinaryOp,
        /// Right-hand operand.
        right: Box<Expr>,
    },
    /// Function invocation with function name and argument expressions.
    FunctionCall {
        /// Name of the function being invoked.
        name: String,
        /// Arguments passed to the function.
        args: Vec<Expr>,
    },
    /// Unary negation expression (`-expr`).
    Negate(Box<Expr>),
}

/// Abstract Syntax Tree node for statements.
#[derive(Debug, Clone, PartialEq)]
pub enum Stmt {
    /// Variable assignment statement (`name = value`).
    Assign {
        /// Target variable name.
        name: String,
        /// Expression to evaluate and assign.
        value: Expr,
    },
    /// Conditional branch statement (`if condition { then_block } else { else_block }`).
    If {
        /// Condition expression to evaluate.
        condition: Expr,
        /// Statements executed if condition evaluates to true.
        then_block: Vec<Stmt>,
        /// Optional statements executed if condition evaluates to false.
        else_block: Option<Vec<Stmt>>,
    },
    /// Emit buy signal statement.
    SignalBuy,
    /// Emit sell signal statement.
    SignalSell,
    /// Standalone expression statement.
    ExprStmt(Expr),
}

/// Execution output signal generated by a strategy script.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Signal {
    /// Buy signal emitted.
    Buy,
    /// Sell signal emitted.
    Sell,
    /// No action / hold position signal.
    Hold,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ast_construction_if_rsi_lt_30_buy() {
        // Arrange: Construct AST for `if rsi(14) < 30 { buy() }`
        let rsi_call = Expr::FunctionCall {
            name: "rsi".to_string(),
            args: vec![Expr::Number(14.0)],
        };
        let condition = Expr::BinaryOp {
            left: Box::new(rsi_call),
            op: BinaryOp::Lt,
            right: Box::new(Expr::Number(30.0)),
        };
        let buy_stmt = Stmt::ExprStmt(Expr::FunctionCall {
            name: "buy".to_string(),
            args: vec![],
        });

        // Act
        let ast = Stmt::If {
            condition: condition.clone(),
            then_block: vec![buy_stmt.clone()],
            else_block: None,
        };

        // Assert
        let expected_ast = Stmt::If {
            condition: Expr::BinaryOp {
                left: Box::new(Expr::FunctionCall {
                    name: "rsi".to_string(),
                    args: vec![Expr::Number(14.0)],
                }),
                op: BinaryOp::Lt,
                right: Box::new(Expr::Number(30.0)),
            },
            then_block: vec![Stmt::ExprStmt(Expr::FunctionCall {
                name: "buy".to_string(),
                args: vec![],
            })],
            else_block: None,
        };

        assert_eq!(ast, expected_ast);
    }

    #[test]
    fn test_ast_construction_with_signal_buy() {
        // Arrange: Construct AST for `if rsi(14) < 30 { SignalBuy }`
        let condition = Expr::BinaryOp {
            left: Box::new(Expr::FunctionCall {
                name: "rsi".to_string(),
                args: vec![Expr::Number(14.0)],
            }),
            op: BinaryOp::Lt,
            right: Box::new(Expr::Number(30.0)),
        };

        // Act
        let ast = Stmt::If {
            condition,
            then_block: vec![Stmt::SignalBuy],
            else_block: Some(vec![Stmt::SignalSell]),
        };

        // Assert
        assert_eq!(
            ast,
            Stmt::If {
                condition: Expr::BinaryOp {
                    left: Box::new(Expr::FunctionCall {
                        name: "rsi".to_string(),
                        args: vec![Expr::Number(14.0)],
                    }),
                    op: BinaryOp::Lt,
                    right: Box::new(Expr::Number(30.0)),
                },
                then_block: vec![Stmt::SignalBuy],
                else_block: Some(vec![Stmt::SignalSell]),
            }
        );
    }

    #[test]
    fn test_binary_op_copy_and_equality() {
        // Arrange
        let op1 = BinaryOp::Add;
        let op2 = op1; // Copy

        // Act & Assert
        assert_eq!(op1, op2);
        assert_eq!(op1, BinaryOp::Add);
        assert_ne!(op1, BinaryOp::Sub);
    }

    #[test]
    fn test_signal_variants() {
        // Arrange
        let buy = Signal::Buy;
        let sell = Signal::Sell;
        let hold = Signal::Hold;

        // Act & Assert
        assert_ne!(buy, sell);
        assert_ne!(sell, hold);
        assert_eq!(buy, Signal::Buy);
    }

    #[test]
    fn test_expr_negate_and_assign() {
        // Arrange
        let expr = Expr::Negate(Box::new(Expr::Identifier("price".to_string())));
        let stmt = Stmt::Assign {
            name: "neg_price".to_string(),
            value: expr.clone(),
        };

        // Act & Assert
        assert_eq!(
            stmt,
            Stmt::Assign {
                name: "neg_price".to_string(),
                value: Expr::Negate(Box::new(Expr::Identifier("price".to_string()))),
            }
        );
    }
}
