//! Paper trading matching engine for simulated order execution.

use omnitrade_core::{Order, OrderStatus, OrderType, Side, Tick};

use crate::error::EngineError;
use crate::fees::{FeeSchedule, SlippageModel};
use crate::fill::{OrderFill, OrderFillBuilder};

/// Matching engine that executes market and limit orders against incoming price ticks.
#[derive(Debug, Clone)]
pub struct MatchingEngine {
    /// Fee schedule applied to executed trades.
    pub fee_schedule: FeeSchedule,
    /// Slippage model applied to execution prices.
    pub slippage_model: SlippageModel,
    /// Monotonic sequence counter tracking execution fills generated by this engine instance.
    pub next_fill_id: u64,
}

impl MatchingEngine {
    /// Creates a new `MatchingEngine` with the given fee schedule and slippage model.
    pub fn new(fee_schedule: FeeSchedule, slippage_model: SlippageModel) -> Self {
        Self {
            fee_schedule,
            slippage_model,
            next_fill_id: 1,
        }
    }

    /// Validates an incoming order size and price prior to submission.
    ///
    /// # Errors
    /// Returns [`EngineError::InvalidOrderSize`] if `quantity <= 0.0`, `quantity.is_nan()`,
    /// or for limit orders if `price <= 0.0` or `price.is_nan()`.
    pub fn submit_order(&self, order: &Order) -> Result<(), EngineError> {
        if order.quantity <= 0.0 || order.quantity.is_nan() {
            return Err(EngineError::InvalidOrderSize {
                size: order.quantity,
                reason: "order quantity must be positive and non-NaN",
            });
        }

        if order.order_type == OrderType::Limit && (order.price <= 0.0 || order.price.is_nan()) {
            return Err(EngineError::InvalidOrderSize {
                size: order.price,
                reason: "limit order price must be positive and non-NaN",
            });
        }

        Ok(())
    }

    /// Processes an incoming market tick against a list of pending orders.
    ///
    /// Returns a vector of generated [`OrderFill`]s and removes completed orders from `pending_orders`.
    pub fn process_tick(&mut self, tick: &Tick, pending_orders: &mut Vec<Order>) -> Vec<OrderFill> {
        let mut fills = Vec::new();

        for order in pending_orders.iter_mut() {
            let (should_fill, fill_base_price, is_maker) = match (order.order_type, order.side) {
                (OrderType::Market, _) => (true, tick.price, false),
                (OrderType::Limit, Side::Buy) if tick.price <= order.price => {
                    (true, order.price, true)
                }
                (OrderType::Limit, Side::Sell) if tick.price >= order.price => {
                    (true, order.price, true)
                }
                _ => (false, 0.0, false),
            };

            if !should_fill {
                continue;
            }

            let fill_qty = order.remaining_quantity();
            if fill_qty <= 0.0 {
                continue;
            }

            let fill_price = self
                .slippage_model
                .apply_slippage(fill_base_price, order.side);
            let notional = fill_price * fill_qty;
            let fee = self.fee_schedule.compute_fee(notional, is_maker);

            order.filled_quantity += fill_qty;
            order.updated_at_ms = tick.timestamp_ms;
            order.status = if order.remaining_quantity() <= f64::EPSILON {
                OrderStatus::Filled
            } else {
                OrderStatus::PartiallyFilled
            };

            self.next_fill_id += 1;

            let fill_builder = OrderFillBuilder::new()
                .order_id(order.id)
                .symbol(order.symbol.clone())
                .side(order.side)
                .fill_price(fill_price)
                .fill_quantity(fill_qty)
                .fee(fee, self.fee_schedule.fee_asset.clone())
                .timestamp_ms(tick.timestamp_ms)
                .is_maker(is_maker);

            match fill_builder.build() {
                Ok(fill) => fills.push(fill),
                Err(err) => {
                    tracing::warn!(
                        "Failed to construct OrderFill for order {}: {:?}",
                        order.id,
                        err
                    );
                }
            }
        }

        pending_orders.retain(|order| order.is_active());
        fills
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use omnitrade_core::TimeInForce;

    fn setup_engine() -> MatchingEngine {
        let fee_schedule =
            FeeSchedule::new(0.001, 0.002, "USDT").expect("fee schedule creation should succeed");
        let slippage_model = SlippageModel::new(10.0).expect("slippage model should succeed");
        MatchingEngine::new(fee_schedule, slippage_model)
    }

    fn create_test_order(
        id: u64,
        side: Side,
        order_type: OrderType,
        price: f64,
        quantity: f64,
    ) -> Order {
        Order {
            id,
            symbol: "BTCUSDT".to_string(),
            side,
            order_type,
            time_in_force: TimeInForce::GTC,
            price,
            stop_price: 0.0,
            quantity,
            filled_quantity: 0.0,
            status: OrderStatus::New,
            created_at_ms: 1000,
            updated_at_ms: 1000,
        }
    }

    #[test]
    fn market_buy_order_filled_at_tick_price_plus_slippage() {
        // Arrange
        let mut engine = setup_engine();
        let order = create_test_order(1, Side::Buy, OrderType::Market, 0.0, 1.0);
        let mut pending = vec![order];
        let tick = Tick::new(2000, 50_000.0, 1.0, false);

        // Act
        let fills = engine.process_tick(&tick, &mut pending);

        // Assert
        assert_eq!(fills.len(), 1);
        let fill = &fills[0];
        // Price with 10 bps slippage: 50,000 * 1.001 = 50,050
        assert!((fill.fill_price - 50_050.0).abs() < 1e-6);
        assert_eq!(fill.fill_quantity, 1.0);
        assert!(!fill.is_maker);
        assert!(pending.is_empty());
    }

    #[test]
    fn market_sell_order_filled_at_tick_price_minus_slippage() {
        // Arrange
        let mut engine = setup_engine();
        let order = create_test_order(2, Side::Sell, OrderType::Market, 0.0, 2.0);
        let mut pending = vec![order];
        let tick = Tick::new(2000, 50_000.0, 2.0, false);

        // Act
        let fills = engine.process_tick(&tick, &mut pending);

        // Assert
        assert_eq!(fills.len(), 1);
        let fill = &fills[0];
        // Price with 10 bps slippage: 50,000 * 0.999 = 49,950
        assert!((fill.fill_price - 49_950.0).abs() < 1e-6);
        assert_eq!(fill.fill_quantity, 2.0);
        assert!(!fill.is_maker);
        assert!(pending.is_empty());
    }

    #[test]
    fn limit_buy_order_triggers_when_tick_price_less_than_or_equal_to_limit() {
        // Arrange
        let mut engine = setup_engine();
        let order = create_test_order(3, Side::Buy, OrderType::Limit, 50_000.0, 1.0);
        let mut pending = vec![order];

        let tick_high = Tick::new(2000, 50_100.0, 1.0, false);
        let tick_equal = Tick::new(2001, 50_000.0, 1.0, false);

        // Act 1: Tick above limit price does not trigger
        let fills_high = engine.process_tick(&tick_high, &mut pending);
        assert!(fills_high.is_empty());
        assert_eq!(pending.len(), 1);

        // Act 2: Tick at limit price triggers fill
        let fills_equal = engine.process_tick(&tick_equal, &mut pending);

        // Assert
        assert_eq!(fills_equal.len(), 1);
        let fill = &fills_equal[0];
        // Price at limit 50,000 * 1.001 = 50,050
        assert!((fill.fill_price - 50_050.0).abs() < 1e-6);
        assert!(fill.is_maker);
        assert!(pending.is_empty());
    }

    #[test]
    fn limit_sell_order_triggers_when_tick_price_greater_than_or_equal_to_limit() {
        // Arrange
        let mut engine = setup_engine();
        let order = create_test_order(4, Side::Sell, OrderType::Limit, 50_000.0, 1.0);
        let mut pending = vec![order];

        let tick_low = Tick::new(2000, 49_900.0, 1.0, false);
        let tick_above = Tick::new(2001, 50_050.0, 1.0, false);

        // Act 1: Tick below limit price does not trigger
        let fills_low = engine.process_tick(&tick_low, &mut pending);
        assert!(fills_low.is_empty());
        assert_eq!(pending.len(), 1);

        // Act 2: Tick above limit price triggers fill
        let fills_above = engine.process_tick(&tick_above, &mut pending);

        // Assert
        assert_eq!(fills_above.len(), 1);
        let fill = &fills_above[0];
        // Price at limit 50,000 * 0.999 = 49,950
        assert!((fill.fill_price - 49_950.0).abs() < 1e-6);
        assert!(fill.is_maker);
        assert!(pending.is_empty());
    }

    #[test]
    fn fee_correctly_deducted() {
        // Arrange
        let mut engine = setup_engine();
        // Maker rate = 0.001, Taker rate = 0.002
        let market_order = create_test_order(5, Side::Buy, OrderType::Market, 0.0, 1.0);
        let mut pending = vec![market_order];
        // Tick price = 10,000, 0 bps slippage for test calculation clarity
        engine.slippage_model = SlippageModel::new(0.0).expect("valid slippage model");
        let tick = Tick::new(2000, 10_000.0, 1.0, false);

        // Act
        let fills = engine.process_tick(&tick, &mut pending);

        // Assert
        assert_eq!(fills.len(), 1);
        let fill = &fills[0];
        let expected_notional = 10_000.0;
        let expected_fee = expected_notional * 0.002; // Taker rate = 0.2% = 20.0
        assert!((fill.fee - expected_fee).abs() < f64::EPSILON);
        assert_eq!(fill.fee_asset, "USDT");
    }

    #[test]
    fn order_status_transitions_to_filled_after_full_execution() {
        // Arrange
        let mut engine = setup_engine();
        let order = create_test_order(6, Side::Buy, OrderType::Market, 0.0, 5.0);
        let mut pending = vec![order];
        let tick = Tick::new(3000, 100.0, 5.0, false);

        // Act
        let _fills = engine.process_tick(&tick, &mut pending);

        // Assert
        assert!(pending.is_empty());
    }

    #[test]
    fn zero_quantity_order_rejected_with_invalid_order_size() {
        // Arrange
        let engine = setup_engine();
        let zero_qty_order = create_test_order(7, Side::Buy, OrderType::Market, 100.0, 0.0);
        let neg_qty_order = create_test_order(8, Side::Buy, OrderType::Market, 100.0, -1.0);
        let nan_qty_order = create_test_order(9, Side::Buy, OrderType::Market, 100.0, f64::NAN);
        let zero_price_limit = create_test_order(10, Side::Buy, OrderType::Limit, 0.0, 1.0);

        // Act & Assert
        assert!(matches!(
            engine.submit_order(&zero_qty_order),
            Err(EngineError::InvalidOrderSize { .. })
        ));
        assert!(matches!(
            engine.submit_order(&neg_qty_order),
            Err(EngineError::InvalidOrderSize { .. })
        ));
        assert!(matches!(
            engine.submit_order(&nan_qty_order),
            Err(EngineError::InvalidOrderSize { .. })
        ));
        assert!(matches!(
            engine.submit_order(&zero_price_limit),
            Err(EngineError::InvalidOrderSize { .. })
        ));
    }
}
