//! Strategy backtesting execution and CSV data parsing module.

use std::error::Error;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};

use omnitrade_core::{Candle, Order, OrderStatus, OrderType, Side, Tick};
use omnitrade_engine::{AccountState, FeeSchedule, MatchingEngine, SlippageModel};
use omnitrade_script::{parse, tokenize, Evaluator, Signal};
use serde::Deserialize;

/// Configuration options for running a backtest simulation.
#[derive(Debug, Clone, PartialEq)]
pub struct BacktestConfig {
    /// Path to the strategy script file.
    pub script_path: PathBuf,
    /// Path to the CSV candle data file.
    pub data_path: PathBuf,
    /// Starting cash balance for the backtest account.
    pub initial_balance: f64,
    /// Trading fee rate (e.g. 0.001 for 0.1%).
    pub fee_rate: f64,
    /// Slippage rate in basis points (e.g. 5.0).
    pub slippage_bps: f64,
    /// Trading symbol identifier (defaults to BTCUSDT).
    pub symbol: String,
    /// Order sizing quantity (defaults to 1.0).
    pub quantity: f64,
}

impl BacktestConfig {
    /// Constructs a new `BacktestConfig` with default symbol and quantity.
    pub fn new(
        script_path: PathBuf,
        data_path: PathBuf,
        initial_balance: f64,
        fee_rate: f64,
        slippage_bps: f64,
    ) -> Self {
        Self {
            script_path,
            data_path,
            initial_balance,
            fee_rate,
            slippage_bps,
            symbol: "BTCUSDT".to_string(),
            quantity: 1.0,
        }
    }
}

/// Performance results generated by a backtest simulation run.
#[derive(Debug, Clone, PartialEq)]
pub struct BacktestResult {
    pub total_pnl: f64,
    pub total_trades: usize,
    pub win_rate: f64,
    pub max_drawdown: f64,
    pub final_balance: f64,
}

#[derive(Debug, Deserialize)]
struct CsvCandleRow {
    timestamp_ms: u64,
    open: f64,
    high: f64,
    low: f64,
    close: f64,
    volume: f64,
}

/// Loads and parses candlestick data from a reader.
pub fn load_candles_from_reader<R: Read>(reader: R) -> Result<Vec<Candle>, Box<dyn Error>> {
    let mut csv_reader = csv::Reader::from_reader(reader);
    let mut candles = Vec::new();
    for result in csv_reader.deserialize() {
        let row: CsvCandleRow = result?;
        candles.push(Candle::new(
            row.timestamp_ms,
            row.open,
            row.high,
            row.low,
            row.close,
            row.volume,
        ));
    }
    Ok(candles)
}

/// Loads and parses candlestick data from a CSV file path.
pub fn load_candles_csv(path: &Path) -> Result<Vec<Candle>, Box<dyn Error>> {
    let file = File::open(path)?;
    load_candles_from_reader(file)
}

fn execute_order(
    acc: &mut AccountState,
    eng: &mut MatchingEngine,
    id: u64,
    sym: &str,
    side: Side,
    qty: f64,
    c: &Candle,
) -> Result<f64, Box<dyn Error>> {
    let order = Order {
        id,
        symbol: sym.to_string(),
        side,
        order_type: OrderType::Market,
        time_in_force: omnitrade_core::TimeInForce::GTC,
        price: c.close,
        stop_price: 0.0,
        quantity: qty,
        filled_quantity: 0.0,
        status: OrderStatus::New,
        created_at_ms: c.timestamp_ms,
        updated_at_ms: c.timestamp_ms,
    };
    let tick = Tick::new(c.timestamp_ms, c.close, qty, false);
    let fills = eng.process_tick(&tick, &mut vec![order]);
    let mut last_price = c.close;
    for fill in fills {
        last_price = fill.fill_price;
        acc.apply_fill(&fill)?;
    }
    Ok(last_price)
}

fn close_pos(
    acc: &mut AccountState,
    eng: &mut MatchingEngine,
    id: u64,
    sym: &str,
    c: &Candle,
) -> Result<f64, Box<dyn Error>> {
    if let Some(pos) = acc.get_position(sym).cloned() {
        let fill_price = execute_order(acc, eng, id, sym, pos.side.opposite(), pos.quantity, c)?;
        let trade_pnl = match pos.side {
            Side::Buy => (fill_price - pos.entry_price) * pos.quantity,
            Side::Sell => (pos.entry_price - fill_price) * pos.quantity,
        };
        Ok(trade_pnl)
    } else {
        Ok(0.0)
    }
}

/// Executes a strategy backtest against historical market candle data.
pub fn run_backtest(cfg: &BacktestConfig) -> Result<BacktestResult, Box<dyn Error>> {
    let script_str = std::fs::read_to_string(&cfg.script_path)?;
    let candles = load_candles_csv(&cfg.data_path)?;
    run_backtest_with_script_and_candles(&script_str, &candles, cfg)
}

fn run_backtest_with_script_and_candles(
    script_str: &str,
    candles: &[Candle],
    cfg: &BacktestConfig,
) -> Result<BacktestResult, Box<dyn Error>> {
    let stmts = parse(&tokenize(script_str)?)?;
    let mut acc = AccountState::new(cfg.initial_balance)?;
    let mut eng = MatchingEngine::new(
        FeeSchedule::new(cfg.fee_rate, cfg.fee_rate, "USDT")?,
        SlippageModel::new(cfg.slippage_bps)?,
    );

    let (mut order_id, mut total_trades, mut wins) = (1u64, 0usize, 0usize);
    let (mut peak_equity, mut max_dd) = (cfg.initial_balance, 0.0f64);
    let mut eval = Evaluator::new();
    let sym = if cfg.symbol.is_empty() {
        "BTCUSDT"
    } else {
        cfg.symbol.as_str()
    };
    let qty = if cfg.quantity <= 0.0 {
        1.0
    } else {
        cfg.quantity
    };

    for i in 0..candles.len() {
        let c = &candles[i];
        let _ = acc.update_unrealized_pnl(sym, c.close);
        let sig = eval.evaluate(&stmts, &candles[0..=i])?;
        let pos_side = acc.get_position(sym).map(|p| p.side);

        match (sig, pos_side) {
            (Signal::Buy, Some(Side::Sell)) | (Signal::Sell, Some(Side::Buy)) => {
                let pnl = close_pos(&mut acc, &mut eng, order_id, sym, c)?;
                order_id += 1;
                total_trades += 1;
                if pnl > 0.0 {
                    wins += 1;
                }
                let new_side = if sig == Signal::Buy {
                    Side::Buy
                } else {
                    Side::Sell
                };
                execute_order(&mut acc, &mut eng, order_id, sym, new_side, qty, c)?;
                order_id += 1;
            }
            (Signal::Buy, None) => {
                execute_order(&mut acc, &mut eng, order_id, sym, Side::Buy, qty, c)?;
                order_id += 1;
            }
            (Signal::Sell, None) => {
                execute_order(&mut acc, &mut eng, order_id, sym, Side::Sell, qty, c)?;
                order_id += 1;
            }
            _ => {}
        }

        let eq = acc.total_equity();
        if eq > peak_equity {
            peak_equity = eq;
        } else if peak_equity > 0.0 {
            max_dd = max_dd.max((peak_equity - eq) / peak_equity);
        }
    }

    if let Some(c) = candles.last() {
        if acc.get_position(sym).is_some() {
            let pnl = close_pos(&mut acc, &mut eng, order_id, sym, c)?;
            total_trades += 1;
            if pnl > 0.0 {
                wins += 1;
            }
        }
    }

    let win_rate = if total_trades > 0 {
        wins as f64 / total_trades as f64
    } else {
        0.0
    };
    Ok(BacktestResult {
        total_pnl: acc.total_pnl(),
        total_trades,
        win_rate,
        max_drawdown: max_dd,
        final_balance: acc.balance,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_csv_data() -> &'static str {
        "timestamp_ms,open,high,low,close,volume\n\
         1000,100.0,105.0,95.0,102.0,500.0\n\
         2000,102.0,108.0,100.0,106.0,600.0\n\
         3000,106.0,110.0,104.0,109.0,700.0\n\
         4000,109.0,115.0,108.0,112.0,800.0\n\
         5000,112.0,120.0,110.0,118.0,900.0"
    }

    fn helper_rising_candles() -> Vec<Candle> {
        vec![
            Candle::new(1000, 100.0, 105.0, 95.0, 100.0, 500.0),
            Candle::new(2000, 110.0, 115.0, 105.0, 110.0, 600.0),
            Candle::new(3000, 120.0, 125.0, 115.0, 120.0, 700.0),
            Candle::new(4000, 130.0, 135.0, 125.0, 130.0, 800.0),
            Candle::new(5000, 140.0, 145.0, 135.0, 140.0, 900.0),
        ]
    }

    #[test]
    fn test_csv_5_rows_parses_into_5_candle_structs() {
        // Arrange & Act
        let candles = load_candles_from_reader(sample_csv_data().as_bytes())
            .expect("CSV reading and parsing should succeed");

        // Assert
        assert_eq!(candles.len(), 5);
        assert_eq!(candles[0].timestamp_ms, 1000);
        assert!((candles[0].open - 100.0).abs() < f64::EPSILON);
        assert!((candles[4].close - 118.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_malformed_csv_row_returns_error() {
        // Arrange
        let csv_data =
            "timestamp_ms,open,high,low,close,volume\n1000,100.0,INVALID,95.0,102.0,500.0";

        // Act & Assert
        assert!(load_candles_from_reader(csv_data.as_bytes()).is_err());
    }

    #[test]
    fn test_backtest_always_buy_script_rising_prices_positive_pnl() {
        // Arrange
        let script = "if close() > 0 { buy() }";
        let candles = helper_rising_candles();
        let config = BacktestConfig::new(
            PathBuf::from("dummy.omni"),
            PathBuf::from("dummy.csv"),
            10000.0,
            0.001,
            5.0,
        );

        // Act
        let result = run_backtest_with_script_and_candles(script, &candles, &config)
            .expect("backtest run should succeed");

        // Assert
        assert!(result.total_pnl > 0.0);
        assert_eq!(result.total_trades, 1);
        assert!((result.win_rate - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_backtest_always_sell_script_rising_prices_negative_pnl() {
        // Arrange
        let script = "if close() > 0 { sell() }";
        let candles = helper_rising_candles();
        let config = BacktestConfig::new(
            PathBuf::from("dummy.omni"),
            PathBuf::from("dummy.csv"),
            10000.0,
            0.001,
            5.0,
        );

        // Act
        let result = run_backtest_with_script_and_candles(script, &candles, &config)
            .expect("backtest run should succeed");

        // Assert
        assert!(result.total_pnl < 0.0);
        assert_eq!(result.total_trades, 1);
        assert!((result.win_rate - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn test_win_rate_computed_as_wins_divided_by_total_trades() {
        // Arrange
        let script = "if close() < 105 { buy() } else { if close() > 115 { sell() } }";
        let candles = vec![
            Candle::new(1000, 100.0, 105.0, 95.0, 100.0, 100.0),
            Candle::new(2000, 120.0, 125.0, 115.0, 120.0, 100.0),
            Candle::new(3000, 130.0, 135.0, 125.0, 130.0, 100.0),
            Candle::new(4000, 100.0, 105.0, 95.0, 100.0, 100.0),
            Candle::new(5000, 110.0, 115.0, 105.0, 110.0, 100.0),
        ];
        let config = BacktestConfig::new(
            PathBuf::from("dummy.omni"),
            PathBuf::from("dummy.csv"),
            10000.0,
            0.0,
            0.0,
        );

        // Act
        let result = run_backtest_with_script_and_candles(script, &candles, &config)
            .expect("backtest should succeed");

        // Assert
        assert_eq!(result.total_trades, 3);
        assert!((result.win_rate - 1.0).abs() < f64::EPSILON);
    }
}
